<?xml version="1.0" encoding="utf-8"?><Database Name="MiBBDD" Class="MiDBContextDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(localdb)\ProjectsV12;Initial Catalog=MiBBDD;Integrated Security=True;Connect Timeout=30" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="MiBBDDConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Categorias" Member="Categorias">
    <Type Name="Categoria">
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Empresas" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Categoria_Subcategoria" Member="Subcategorias" ThisKey="Nombre" OtherKey="Categoria" Type="Subcategoria" />
    </Type>
  </Table>
  <Table Name="dbo.Subcategorias" Member="Subcategorias">
    <Type Name="Subcategoria">
      <Column Name="Categoria" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Empresas" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Categoria_Subcategoria" Member="Categoria1" ThisKey="Categoria" OtherKey="Nombre" Type="Categoria" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Clientes" Member="Clientes">
    <Type Name="Cliente">
      <Column Name="SS" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Apellidos" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Telefono" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Edad" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Cliente_Direccion" Member="Direccions" ThisKey="SS" OtherKey="Dueño" Type="Direccion" Cardinality="One" />
      <Association Name="Cliente_Pedido" Member="Pedidos" ThisKey="SS" OtherKey="IDCliente" Type="Pedido" />
      <Association Name="Pedido_Cliente" Member="Pedido" ThisKey="SS" OtherKey="IDCliente" Type="Pedido" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Direcciones" Member="Direccions">
    <Type Name="Direccion">
      <Column Name="Dueño" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Calle" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Numero" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Puerta" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="[Codigo Postal]" Member="Codigo_Postal" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Detalles" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Portal" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Piso" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Cliente_Direccion" Member="Cliente" ThisKey="Dueño" OtherKey="SS" Type="Cliente" IsForeignKey="true" />
      <Association Name="Empresa_Direccion" Member="Empresa" ThisKey="Dueño" OtherKey="IDEmpresa" Type="Empresa" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Empresas" Member="Empresas">
    <Type Name="Empresa">
      <Column Name="IDEmpresa" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Subcategoria" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Telefono" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Valoracion" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Categoria" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Empresa_Direccion" Member="Direccions" ThisKey="IDEmpresa" OtherKey="Dueño" Type="Direccion" Cardinality="One" />
      <Association Name="Empresa_Pedido" Member="Pedidos" ThisKey="IDEmpresa" OtherKey="IDEmpresa" Type="Pedido" />
      <Association Name="Empresa_Item" Member="Items" ThisKey="IDEmpresa" OtherKey="IDEmpresa" Type="Item" />
      <Association Name="Pedido_Empresa" Member="Pedido" ThisKey="IDEmpresa" OtherKey="IDEmpresa" Type="Pedido" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Pedidos" Member="Pedidos">
    <Type Name="Pedido">
      <Column Name="IDPedido" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IDEmpresa" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="IDItem" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IDCliente" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Hora" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Estado" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Oculto" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Pedido_Cliente" Member="Clientes" ThisKey="IDCliente" OtherKey="SS" Type="Cliente" Cardinality="One" />
      <Association Name="Pedido_Empresa" Member="Empresas" ThisKey="IDEmpresa" OtherKey="IDEmpresa" Type="Empresa" Cardinality="One" />
      <Association Name="Pedido_Item" Member="Items" ThisKey="IDItem" OtherKey="IDItem" Type="Item" Cardinality="One" />
      <Association Name="Cliente_Pedido" Member="Cliente" ThisKey="IDCliente" OtherKey="SS" Type="Cliente" IsForeignKey="true" />
      <Association Name="Empresa_Pedido" Member="Empresa" ThisKey="IDEmpresa" OtherKey="IDEmpresa" Type="Empresa" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Items" Member="Items">
    <Type Name="Item">
      <Column Name="IDItem" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Precio" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="IDEmpresa" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Association Name="Pedido_Item" Member="Pedido" ThisKey="IDItem" OtherKey="IDItem" Type="Pedido" IsForeignKey="true" />
      <Association Name="Empresa_Item" Member="Empresa" ThisKey="IDEmpresa" OtherKey="IDEmpresa" Type="Empresa" IsForeignKey="true" />
    </Type>
  </Table>
</Database>