#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthCare.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="MiBBDD")]
	public partial class MiDBContextDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertClientes(Clientes instance);
    partial void UpdateClientes(Clientes instance);
    partial void DeleteClientes(Clientes instance);
    partial void InsertDirecciones(Direcciones instance);
    partial void UpdateDirecciones(Direcciones instance);
    partial void DeleteDirecciones(Direcciones instance);
    partial void InsertItems(Items instance);
    partial void UpdateItems(Items instance);
    partial void DeleteItems(Items instance);
    partial void InsertPrescripciones(Prescripciones instance);
    partial void UpdatePrescripciones(Prescripciones instance);
    partial void DeletePrescripciones(Prescripciones instance);
    partial void InsertEmpresas(Empresas instance);
    partial void UpdateEmpresas(Empresas instance);
    partial void DeleteEmpresas(Empresas instance);
    partial void InsertSolicitudes(Solicitudes instance);
    partial void UpdateSolicitudes(Solicitudes instance);
    partial void DeleteSolicitudes(Solicitudes instance);
    #endregion
		
		public MiDBContextDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["MiBBDDConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public MiDBContextDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MiDBContextDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MiDBContextDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MiDBContextDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Clientes> Clientes
		{
			get
			{
				return this.GetTable<Clientes>();
			}
		}
		
		public System.Data.Linq.Table<Direcciones> Direcciones
		{
			get
			{
				return this.GetTable<Direcciones>();
			}
		}
		
		public System.Data.Linq.Table<Items> Items
		{
			get
			{
				return this.GetTable<Items>();
			}
		}
		
		public System.Data.Linq.Table<Prescripciones> Prescripciones
		{
			get
			{
				return this.GetTable<Prescripciones>();
			}
		}
		
		public System.Data.Linq.Table<Empresas> Empresas
		{
			get
			{
				return this.GetTable<Empresas>();
			}
		}
		
		public System.Data.Linq.Table<Solicitudes> Solicitudes
		{
			get
			{
				return this.GetTable<Solicitudes>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Clientes")]
	public partial class Clientes : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SS;
		
		private string _Nombre;
		
		private string _Apellidos;
		
		private int _Telefono;
		
		private int _Edad;
		
		private string _Email;
		
		private EntityRef<Direcciones> _Direcciones;
		
		private EntitySet<Prescripciones> _Prescripciones;
		
		private EntityRef<Solicitudes> _Solicitudes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSSChanging(int value);
    partial void OnSSChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnApellidosChanging(string value);
    partial void OnApellidosChanged();
    partial void OnTelefonoChanging(int value);
    partial void OnTelefonoChanged();
    partial void OnEdadChanging(int value);
    partial void OnEdadChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    #endregion
		
		public Clientes()
		{
			this._Direcciones = default(EntityRef<Direcciones>);
			this._Prescripciones = new EntitySet<Prescripciones>(new Action<Prescripciones>(this.attach_Prescripciones), new Action<Prescripciones>(this.detach_Prescripciones));
			this._Solicitudes = default(EntityRef<Solicitudes>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SS", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int SS
		{
			get
			{
				return this._SS;
			}
			set
			{
				if ((this._SS != value))
				{
					if (this._Solicitudes.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSSChanging(value);
					this.SendPropertyChanging();
					this._SS = value;
					this.SendPropertyChanged("SS");
					this.OnSSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellidos", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Apellidos
		{
			get
			{
				return this._Apellidos;
			}
			set
			{
				if ((this._Apellidos != value))
				{
					this.OnApellidosChanging(value);
					this.SendPropertyChanging();
					this._Apellidos = value;
					this.SendPropertyChanged("Apellidos");
					this.OnApellidosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="Int NOT NULL")]
		public int Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this.OnTelefonoChanging(value);
					this.SendPropertyChanging();
					this._Telefono = value;
					this.SendPropertyChanged("Telefono");
					this.OnTelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Edad", DbType="Int NOT NULL")]
		public int Edad
		{
			get
			{
				return this._Edad;
			}
			set
			{
				if ((this._Edad != value))
				{
					this.OnEdadChanging(value);
					this.SendPropertyChanging();
					this._Edad = value;
					this.SendPropertyChanged("Edad");
					this.OnEdadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Clientes_Direcciones", Storage="_Direcciones", ThisKey="SS", OtherKey="IDDueño", IsUnique=true, IsForeignKey=false)]
		public Direcciones Direcciones
		{
			get
			{
				return this._Direcciones.Entity;
			}
			set
			{
				Direcciones previousValue = this._Direcciones.Entity;
				if (((previousValue != value) 
							|| (this._Direcciones.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Direcciones.Entity = null;
						previousValue.Clientes = null;
					}
					this._Direcciones.Entity = value;
					if ((value != null))
					{
						value.Clientes = this;
					}
					this.SendPropertyChanged("Direcciones");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Clientes_Prescripciones", Storage="_Prescripciones", ThisKey="SS", OtherKey="IDCliente")]
		public EntitySet<Prescripciones> Prescripciones
		{
			get
			{
				return this._Prescripciones;
			}
			set
			{
				this._Prescripciones.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Solicitudes_Clientes", Storage="_Solicitudes", ThisKey="SS", OtherKey="IdCliente", IsForeignKey=true)]
		public Solicitudes Solicitudes
		{
			get
			{
				return this._Solicitudes.Entity;
			}
			set
			{
				Solicitudes previousValue = this._Solicitudes.Entity;
				if (((previousValue != value) 
							|| (this._Solicitudes.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Solicitudes.Entity = null;
						previousValue.Clientes = null;
					}
					this._Solicitudes.Entity = value;
					if ((value != null))
					{
						value.Clientes = this;
						this._SS = value.IdCliente;
					}
					else
					{
						this._SS = default(int);
					}
					this.SendPropertyChanged("Solicitudes");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Prescripciones(Prescripciones entity)
		{
			this.SendPropertyChanging();
			entity.Clientes = this;
		}
		
		private void detach_Prescripciones(Prescripciones entity)
		{
			this.SendPropertyChanging();
			entity.Clientes = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Direcciones")]
	public partial class Direcciones : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDDueño;
		
		private string _Calle;
		
		private int _Numero;
		
		private string _Puerta;
		
		private int _Codigo_Postal;
		
		private string _Detalles;
		
		private System.Nullable<int> _Portal;
		
		private System.Nullable<int> _Piso;
		
		private EntityRef<Clientes> _Clientes;
		
		private EntityRef<Empresas> _Empresas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDDueñoChanging(int value);
    partial void OnIDDueñoChanged();
    partial void OnCalleChanging(string value);
    partial void OnCalleChanged();
    partial void OnNumeroChanging(int value);
    partial void OnNumeroChanged();
    partial void OnPuertaChanging(string value);
    partial void OnPuertaChanged();
    partial void OnCodigo_PostalChanging(int value);
    partial void OnCodigo_PostalChanged();
    partial void OnDetallesChanging(string value);
    partial void OnDetallesChanged();
    partial void OnPortalChanging(System.Nullable<int> value);
    partial void OnPortalChanged();
    partial void OnPisoChanging(System.Nullable<int> value);
    partial void OnPisoChanged();
    #endregion
		
		public Direcciones()
		{
			this._Clientes = default(EntityRef<Clientes>);
			this._Empresas = default(EntityRef<Empresas>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDDueño", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IDDueño
		{
			get
			{
				return this._IDDueño;
			}
			set
			{
				if ((this._IDDueño != value))
				{
					if ((this._Clientes.HasLoadedOrAssignedValue || this._Empresas.HasLoadedOrAssignedValue))
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDDueñoChanging(value);
					this.SendPropertyChanging();
					this._IDDueño = value;
					this.SendPropertyChanged("IDDueño");
					this.OnIDDueñoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Calle", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Calle
		{
			get
			{
				return this._Calle;
			}
			set
			{
				if ((this._Calle != value))
				{
					this.OnCalleChanging(value);
					this.SendPropertyChanging();
					this._Calle = value;
					this.SendPropertyChanged("Calle");
					this.OnCalleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Numero", DbType="Int NOT NULL")]
		public int Numero
		{
			get
			{
				return this._Numero;
			}
			set
			{
				if ((this._Numero != value))
				{
					this.OnNumeroChanging(value);
					this.SendPropertyChanging();
					this._Numero = value;
					this.SendPropertyChanged("Numero");
					this.OnNumeroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Puerta", DbType="NChar(10)")]
		public string Puerta
		{
			get
			{
				return this._Puerta;
			}
			set
			{
				if ((this._Puerta != value))
				{
					this.OnPuertaChanging(value);
					this.SendPropertyChanging();
					this._Puerta = value;
					this.SendPropertyChanged("Puerta");
					this.OnPuertaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Codigo Postal]", Storage="_Codigo_Postal", DbType="Int NOT NULL")]
		public int Codigo_Postal
		{
			get
			{
				return this._Codigo_Postal;
			}
			set
			{
				if ((this._Codigo_Postal != value))
				{
					this.OnCodigo_PostalChanging(value);
					this.SendPropertyChanging();
					this._Codigo_Postal = value;
					this.SendPropertyChanged("Codigo_Postal");
					this.OnCodigo_PostalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Detalles", DbType="NVarChar(MAX)")]
		public string Detalles
		{
			get
			{
				return this._Detalles;
			}
			set
			{
				if ((this._Detalles != value))
				{
					this.OnDetallesChanging(value);
					this.SendPropertyChanging();
					this._Detalles = value;
					this.SendPropertyChanged("Detalles");
					this.OnDetallesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Portal", DbType="Int")]
		public System.Nullable<int> Portal
		{
			get
			{
				return this._Portal;
			}
			set
			{
				if ((this._Portal != value))
				{
					this.OnPortalChanging(value);
					this.SendPropertyChanging();
					this._Portal = value;
					this.SendPropertyChanged("Portal");
					this.OnPortalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Piso", DbType="Int")]
		public System.Nullable<int> Piso
		{
			get
			{
				return this._Piso;
			}
			set
			{
				if ((this._Piso != value))
				{
					this.OnPisoChanging(value);
					this.SendPropertyChanging();
					this._Piso = value;
					this.SendPropertyChanged("Piso");
					this.OnPisoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Clientes_Direcciones", Storage="_Clientes", ThisKey="IDDueño", OtherKey="SS", IsForeignKey=true)]
		public Clientes Clientes
		{
			get
			{
				return this._Clientes.Entity;
			}
			set
			{
				Clientes previousValue = this._Clientes.Entity;
				if (((previousValue != value) 
							|| (this._Clientes.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Clientes.Entity = null;
						previousValue.Direcciones = null;
					}
					this._Clientes.Entity = value;
					if ((value != null))
					{
						value.Direcciones = this;
						this._IDDueño = value.SS;
					}
					else
					{
						this._IDDueño = default(int);
					}
					this.SendPropertyChanged("Clientes");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Empresas_Direcciones", Storage="_Empresas", ThisKey="IDDueño", OtherKey="IDEmpresa", IsForeignKey=true)]
		public Empresas Empresas
		{
			get
			{
				return this._Empresas.Entity;
			}
			set
			{
				Empresas previousValue = this._Empresas.Entity;
				if (((previousValue != value) 
							|| (this._Empresas.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Empresas.Entity = null;
						previousValue.Direcciones = null;
					}
					this._Empresas.Entity = value;
					if ((value != null))
					{
						value.Direcciones = this;
						this._IDDueño = value.IDEmpresa;
					}
					else
					{
						this._IDDueño = default(int);
					}
					this.SendPropertyChanged("Empresas");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Items")]
	public partial class Items : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDItem;
		
		private int _IDPrescripcion;
		
		private string _Nombre;
		
		private string _Tipo;
		
		private string _Detalles;
		
		private EntityRef<Prescripciones> _Prescripciones;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDItemChanging(int value);
    partial void OnIDItemChanged();
    partial void OnIDPrescripcionChanging(int value);
    partial void OnIDPrescripcionChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnTipoChanging(string value);
    partial void OnTipoChanged();
    partial void OnDetallesChanging(string value);
    partial void OnDetallesChanged();
    #endregion
		
		public Items()
		{
			this._Prescripciones = default(EntityRef<Prescripciones>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDItem", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IDItem
		{
			get
			{
				return this._IDItem;
			}
			set
			{
				if ((this._IDItem != value))
				{
					this.OnIDItemChanging(value);
					this.SendPropertyChanging();
					this._IDItem = value;
					this.SendPropertyChanged("IDItem");
					this.OnIDItemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDPrescripcion", DbType="Int NOT NULL")]
		public int IDPrescripcion
		{
			get
			{
				return this._IDPrescripcion;
			}
			set
			{
				if ((this._IDPrescripcion != value))
				{
					if (this._Prescripciones.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDPrescripcionChanging(value);
					this.SendPropertyChanging();
					this._IDPrescripcion = value;
					this.SendPropertyChanged("IDPrescripcion");
					this.OnIDPrescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tipo", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Tipo
		{
			get
			{
				return this._Tipo;
			}
			set
			{
				if ((this._Tipo != value))
				{
					this.OnTipoChanging(value);
					this.SendPropertyChanging();
					this._Tipo = value;
					this.SendPropertyChanged("Tipo");
					this.OnTipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Detalles", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Detalles
		{
			get
			{
				return this._Detalles;
			}
			set
			{
				if ((this._Detalles != value))
				{
					this.OnDetallesChanging(value);
					this.SendPropertyChanging();
					this._Detalles = value;
					this.SendPropertyChanged("Detalles");
					this.OnDetallesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Prescripciones_Items", Storage="_Prescripciones", ThisKey="IDPrescripcion", OtherKey="IDPrescripcion", IsForeignKey=true)]
		public Prescripciones Prescripciones
		{
			get
			{
				return this._Prescripciones.Entity;
			}
			set
			{
				Prescripciones previousValue = this._Prescripciones.Entity;
				if (((previousValue != value) 
							|| (this._Prescripciones.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Prescripciones.Entity = null;
						previousValue.Items.Remove(this);
					}
					this._Prescripciones.Entity = value;
					if ((value != null))
					{
						value.Items.Add(this);
						this._IDPrescripcion = value.IDPrescripcion;
					}
					else
					{
						this._IDPrescripcion = default(int);
					}
					this.SendPropertyChanged("Prescripciones");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Prescripciones")]
	public partial class Prescripciones : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDPrescripcion;
		
		private int _IDCliente;
		
		private int _IDEmpleado;
		
		private string _Seguro;
		
		private int _Estado;
		
		private EntitySet<Items> _Items;
		
		private EntityRef<Empresas> _Empresas;
		
		private EntityRef<Clientes> _Clientes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDPrescripcionChanging(int value);
    partial void OnIDPrescripcionChanged();
    partial void OnIDClienteChanging(int value);
    partial void OnIDClienteChanged();
    partial void OnIDEmpresaChanging(int value);
    partial void OnIDEmpresaChanged();
    partial void OnSeguroChanging(string value);
    partial void OnSeguroChanged();
    partial void OnEstadoChanging(int value);
    partial void OnEstadoChanged();
    #endregion
		
		public Prescripciones()
		{
			this._Items = new EntitySet<Items>(new Action<Items>(this.attach_Items), new Action<Items>(this.detach_Items));
			this._Empresas = default(EntityRef<Empresas>);
			this._Clientes = default(EntityRef<Clientes>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDPrescripcion", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IDPrescripcion
		{
			get
			{
				return this._IDPrescripcion;
			}
			set
			{
				if ((this._IDPrescripcion != value))
				{
					this.OnIDPrescripcionChanging(value);
					this.SendPropertyChanging();
					this._IDPrescripcion = value;
					this.SendPropertyChanged("IDPrescripcion");
					this.OnIDPrescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDCliente", DbType="Int NOT NULL")]
		public int IDCliente
		{
			get
			{
				return this._IDCliente;
			}
			set
			{
				if ((this._IDCliente != value))
				{
					if (this._Clientes.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDClienteChanging(value);
					this.SendPropertyChanging();
					this._IDCliente = value;
					this.SendPropertyChanged("IDCliente");
					this.OnIDClienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="IDEmpleado", Storage="_IDEmpleado", DbType="Int NOT NULL")]
		public int IDEmpresa
		{
			get
			{
				return this._IDEmpleado;
			}
			set
			{
				if ((this._IDEmpleado != value))
				{
					this.OnIDEmpresaChanging(value);
					this.SendPropertyChanging();
					this._IDEmpleado = value;
					this.SendPropertyChanged("IDEmpresa");
					this.OnIDEmpresaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Seguro", DbType="NVarChar(50)")]
		public string Seguro
		{
			get
			{
				return this._Seguro;
			}
			set
			{
				if ((this._Seguro != value))
				{
					this.OnSeguroChanging(value);
					this.SendPropertyChanging();
					this._Seguro = value;
					this.SendPropertyChanged("Seguro");
					this.OnSeguroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado")]
		public int Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Prescripciones_Items", Storage="_Items", ThisKey="IDPrescripcion", OtherKey="IDPrescripcion")]
		public EntitySet<Items> Items
		{
			get
			{
				return this._Items;
			}
			set
			{
				this._Items.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Prescripciones_Empresas", Storage="_Empresas", ThisKey="IDEmpresa", OtherKey="IDEmpresa", IsUnique=true, IsForeignKey=false)]
		public Empresas Empresas
		{
			get
			{
				return this._Empresas.Entity;
			}
			set
			{
				Empresas previousValue = this._Empresas.Entity;
				if (((previousValue != value) 
							|| (this._Empresas.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Empresas.Entity = null;
						previousValue.Prescripciones = null;
					}
					this._Empresas.Entity = value;
					if ((value != null))
					{
						value.Prescripciones = this;
					}
					this.SendPropertyChanged("Empresas");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Clientes_Prescripciones", Storage="_Clientes", ThisKey="IDCliente", OtherKey="SS", IsForeignKey=true)]
		public Clientes Clientes
		{
			get
			{
				return this._Clientes.Entity;
			}
			set
			{
				Clientes previousValue = this._Clientes.Entity;
				if (((previousValue != value) 
							|| (this._Clientes.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Clientes.Entity = null;
						previousValue.Prescripciones.Remove(this);
					}
					this._Clientes.Entity = value;
					if ((value != null))
					{
						value.Prescripciones.Add(this);
						this._IDCliente = value.SS;
					}
					else
					{
						this._IDCliente = default(int);
					}
					this.SendPropertyChanged("Clientes");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Items(Items entity)
		{
			this.SendPropertyChanging();
			entity.Prescripciones = this;
		}
		
		private void detach_Items(Items entity)
		{
			this.SendPropertyChanging();
			entity.Prescripciones = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Empresas")]
	public partial class Empresas : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDEmpresa;
		
		private string _Nombre;
		
		private string _Especializacion;
		
		private int _Telefono;
		
		private string _Email;
		
		private string _Descripcion;
		
		private int _Valoracion;
		
		private string _Sector;
		
		private EntityRef<Direcciones> _Direcciones;
		
		private EntityRef<Prescripciones> _Prescripciones;
		
		private EntityRef<Solicitudes> _Solicitudes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDEmpresaChanging(int value);
    partial void OnIDEmpresaChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnEspecializacionChanging(string value);
    partial void OnEspecializacionChanged();
    partial void OnTelefonoChanging(int value);
    partial void OnTelefonoChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    partial void OnValoracionChanging(int value);
    partial void OnValoracionChanged();
    partial void OnSectorChanging(string value);
    partial void OnSectorChanged();
    #endregion
		
		public Empresas()
		{
			this._Direcciones = default(EntityRef<Direcciones>);
			this._Prescripciones = default(EntityRef<Prescripciones>);
			this._Solicitudes = default(EntityRef<Solicitudes>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDEmpresa", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IDEmpresa
		{
			get
			{
				return this._IDEmpresa;
			}
			set
			{
				if ((this._IDEmpresa != value))
				{
					if ((this._Prescripciones.HasLoadedOrAssignedValue || this._Solicitudes.HasLoadedOrAssignedValue))
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDEmpresaChanging(value);
					this.SendPropertyChanging();
					this._IDEmpresa = value;
					this.SendPropertyChanged("IDEmpresa");
					this.OnIDEmpresaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Especializacion", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Especializacion
		{
			get
			{
				return this._Especializacion;
			}
			set
			{
				if ((this._Especializacion != value))
				{
					this.OnEspecializacionChanging(value);
					this.SendPropertyChanging();
					this._Especializacion = value;
					this.SendPropertyChanged("Especializacion");
					this.OnEspecializacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="Int NOT NULL")]
		public int Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this.OnTelefonoChanging(value);
					this.SendPropertyChanging();
					this._Telefono = value;
					this.SendPropertyChanged("Telefono");
					this.OnTelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(MAX)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="NVarChar(MAX)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this.OnDescripcionChanging(value);
					this.SendPropertyChanging();
					this._Descripcion = value;
					this.SendPropertyChanged("Descripcion");
					this.OnDescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Valoracion", DbType="Int NOT NULL")]
		public int Valoracion
		{
			get
			{
				return this._Valoracion;
			}
			set
			{
				if ((this._Valoracion != value))
				{
					this.OnValoracionChanging(value);
					this.SendPropertyChanging();
					this._Valoracion = value;
					this.SendPropertyChanged("Valoracion");
					this.OnValoracionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sector", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Sector
		{
			get
			{
				return this._Sector;
			}
			set
			{
				if ((this._Sector != value))
				{
					this.OnSectorChanging(value);
					this.SendPropertyChanging();
					this._Sector = value;
					this.SendPropertyChanged("Sector");
					this.OnSectorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Empresas_Direcciones", Storage="_Direcciones", ThisKey="IDEmpresa", OtherKey="IDDueño", IsUnique=true, IsForeignKey=false)]
		public Direcciones Direcciones
		{
			get
			{
				return this._Direcciones.Entity;
			}
			set
			{
				Direcciones previousValue = this._Direcciones.Entity;
				if (((previousValue != value) 
							|| (this._Direcciones.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Direcciones.Entity = null;
						previousValue.Empresas = null;
					}
					this._Direcciones.Entity = value;
					if ((value != null))
					{
						value.Empresas = this;
					}
					this.SendPropertyChanged("Direcciones");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Prescripciones_Empresas", Storage="_Prescripciones", ThisKey="IDEmpresa", OtherKey="IDEmpresa", IsForeignKey=true)]
		public Prescripciones Prescripciones
		{
			get
			{
				return this._Prescripciones.Entity;
			}
			set
			{
				Prescripciones previousValue = this._Prescripciones.Entity;
				if (((previousValue != value) 
							|| (this._Prescripciones.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Prescripciones.Entity = null;
						previousValue.Empresas = null;
					}
					this._Prescripciones.Entity = value;
					if ((value != null))
					{
						value.Empresas = this;
						this._IDEmpresa = value.IDEmpresa;
					}
					else
					{
						this._IDEmpresa = default(int);
					}
					this.SendPropertyChanged("Prescripciones");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Solicitudes_Empresas", Storage="_Solicitudes", ThisKey="IDEmpresa", OtherKey="idEmpresa", IsForeignKey=true)]
		public Solicitudes Solicitudes
		{
			get
			{
				return this._Solicitudes.Entity;
			}
			set
			{
				Solicitudes previousValue = this._Solicitudes.Entity;
				if (((previousValue != value) 
							|| (this._Solicitudes.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Solicitudes.Entity = null;
						previousValue.Empresas = null;
					}
					this._Solicitudes.Entity = value;
					if ((value != null))
					{
						value.Empresas = this;
						this._IDEmpresa = value.idEmpresa;
					}
					else
					{
						this._IDEmpresa = default(int);
					}
					this.SendPropertyChanged("Solicitudes");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Solicitudes")]
	public partial class Solicitudes : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdCliente;
		
		private int _idEmpresa;
		
		private System.DateTime _hora;
		
		private EntityRef<Clientes> _Clientes;
		
		private EntityRef<Empresas> _Empresas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdClienteChanging(int value);
    partial void OnIdClienteChanged();
    partial void OnidEmpresaChanging(int value);
    partial void OnidEmpresaChanged();
    partial void OnhoraChanging(System.DateTime value);
    partial void OnhoraChanged();
    #endregion
		
		public Solicitudes()
		{
			this._Clientes = default(EntityRef<Clientes>);
			this._Empresas = default(EntityRef<Empresas>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCliente", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdCliente
		{
			get
			{
				return this._IdCliente;
			}
			set
			{
				if ((this._IdCliente != value))
				{
					this.OnIdClienteChanging(value);
					this.SendPropertyChanging();
					this._IdCliente = value;
					this.SendPropertyChanged("IdCliente");
					this.OnIdClienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idEmpresa", DbType="Int NOT NULL")]
		public int idEmpresa
		{
			get
			{
				return this._idEmpresa;
			}
			set
			{
				if ((this._idEmpresa != value))
				{
					this.OnidEmpresaChanging(value);
					this.SendPropertyChanging();
					this._idEmpresa = value;
					this.SendPropertyChanged("idEmpresa");
					this.OnidEmpresaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hora", DbType="Date NOT NULL")]
		public System.DateTime hora
		{
			get
			{
				return this._hora;
			}
			set
			{
				if ((this._hora != value))
				{
					this.OnhoraChanging(value);
					this.SendPropertyChanging();
					this._hora = value;
					this.SendPropertyChanged("hora");
					this.OnhoraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Solicitudes_Clientes", Storage="_Clientes", ThisKey="IdCliente", OtherKey="SS", IsUnique=true, IsForeignKey=false)]
		public Clientes Clientes
		{
			get
			{
				return this._Clientes.Entity;
			}
			set
			{
				Clientes previousValue = this._Clientes.Entity;
				if (((previousValue != value) 
							|| (this._Clientes.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Clientes.Entity = null;
						previousValue.Solicitudes = null;
					}
					this._Clientes.Entity = value;
					if ((value != null))
					{
						value.Solicitudes = this;
					}
					this.SendPropertyChanged("Clientes");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Solicitudes_Empresas", Storage="_Empresas", ThisKey="idEmpresa", OtherKey="IDEmpresa", IsUnique=true, IsForeignKey=false)]
		public Empresas Empresas
		{
			get
			{
				return this._Empresas.Entity;
			}
			set
			{
				Empresas previousValue = this._Empresas.Entity;
				if (((previousValue != value) 
							|| (this._Empresas.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Empresas.Entity = null;
						previousValue.Solicitudes = null;
					}
					this._Empresas.Entity = value;
					if ((value != null))
					{
						value.Solicitudes = this;
					}
					this.SendPropertyChanged("Empresas");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
